// base
export const UPDATE_REQUEST_STATUS = 'UPDATE_REQUEST_STATUS'
//popup
export const SHOW_MODAL_NEW_CUSTOMER = 'SHOW_MODAL_NEW_CUSTOMER'
export const CLOSE_MODAL_NEW_CUSTOMER = 'CLOSE_MODAL_NEW_CUSTOMER'
