// base
export const UPDATE_REQUEST_STATUS = 'UPDATE_REQUEST_STATUS'
//popup
export const SHOW_MODAL_WELCOME_CUSTOMER = 'SHOW_MODAL_WELCOME_CUSTOMER'
export const CLOSE_MODAL_WELCOME_CUSTOMER = 'CLOSE_MODAL_WELCOME_CUSTOMER'
