// base
export const UPDATE_REQUEST_STATUS = 'UPDATE_REQUEST_STATUS'
//popup
export const SHOW_MODAL_WELCOME_CUSTOMER = 'SHOW_MODAL_WELCOME_CUSTOMER'
export const CLOSE_MODAL_WELCOME_CUSTOMER = 'CLOSE_MODAL_WELCOME_CUSTOMER'
// form initial
export const SET_INITIAL_VALUES_FORM_REQUEST = 'SET_INITIAL_VALUES_FORM_REQUEST'
